# Build settings
markdown: kramdown
theme: minima

title: "ScalrX GameDev"
author: "Scalr"
description: >
  An assortment of my professional works such as teachings and technical write-ups.
twitter_username: scalrx
github_username: scalrx
rss: rss

show_excerpts: false

plugins:
 - jekyll-feed
 - jekyll-seo-tag

header_pages:
 - teachings.md
 
minima:
date_format: "%b %-d, %Y"
